### ISSUE TITLE
QMI driver build fails

### ISSUE THREAD

**Issue by dvemer** [estkme-group/lpac#203]
Hi, I'm trying to build latest lpac with QMI driver:

`option(LPAC_WITH_APDU_QMI "Build QMI backend for Qualcomm devices (requires libqmi)" ON)`

But get the following error:
```
[  6%] Built target cjson-static
[ 37%] Built target euicc
[ 39%] Building C object driver/CMakeFiles/euicc-drivers.dir/apdu/qmi.c.o
In file included from /home/ffh/work/LTE/src/lpac/driver/apdu/qmi_common.h:8,
                 from /home/ffh/work/LTE/src/lpac/driver/apdu/qmi.c:8:
/home/ffh/work/LTE/src/lpac/driver/apdu/qmi_helpers.h:49:1: error: unknown type name ‘QmiMessageUimOpenLogicalChannelOutput’
   49 | QmiMessageUimOpenLogicalChannelOutput *
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ffh/work/LTE/src/lpac/driver/apdu/qmi_helpers.h:52:5: error: unknown type name ‘QmiMessageUimOpenLogicalChannelInput’
   52 |     QmiMessageUimOpenLogicalChannelInput *input,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ffh/work/LTE/src/lpac/driver/apdu/qmi_helpers.h:56:1: error: unknown type name ‘QmiMessageUimLogicalChannelOutput’; did you mean ‘QmiMessageVoiceDialCallOutput’?
   56 | QmiMessageUimLogicalChannelOutput *
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | QmiMessageVoiceDialCallOutput
/home/ffh/work/LTE/src/lpac/driver/apdu/qmi_helpers.h:59:5: error: unknown type name ‘QmiMessageUimLogicalChannelInput’; did you mean ‘QmiMessageVoiceDialCallInput’?
   59 |     QmiMessageUimLogicalChannelInput *input,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     QmiMessageVoiceDialCallInput
/home/ffh/work/LTE/src/lpac/driver/apdu/qmi_helpers.h:63:1: error: unknown type name ‘QmiMessageUimSendApduOutput’; did you mean ‘QmiMessageWmsSendAckOutput’?
   63 | QmiMessageUimSendApduOutput *
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      | QmiMessageWmsSendAckOutput
/home/ffh/work/LTE/src/lpac/driver/apdu/qmi_helpers.h:66:5: error: unknown type name ‘QmiMessageUimSendApduInput’; did you mean ‘QmiMessageWmsSendAckInput’?
   66 |     QmiMessageUimSendApduInput *input,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     QmiMessageWmsSendAckInput
```

Where I can get these structure definitions ? libqmi-glib is installed, i'm working on Ubunto 20.04.

Thanks

**Comment by septs** [comment]
> The qmi drivers require libqmi 1.35.5 or later version, so you have to compile libqmi first.

from <https://github.com/estkme-group/lpac/issues/142#issuecomment-2267957265>

**Comment by damonto** [comment]
Since the new version of libqmi has not been officially released, you need to compile libqmi manually.

For detailed build instructions, refer to [libqmi's official documentation](https://modemmanager.org/docs/libqmi/building/building-meson/).

If you already have libqmi version 1.35.5 or later installed, you can skip this step.

```bash
# sudo pacman -S --needed meson ninja pkg-config bash-completion libgirepository help2man glib2 libgudev libmbim libqrtr-glib (Arch Linux)
# sudo apt-get install -y meson ninja-build pkg-config bash-completion libgirepository1.0-dev help2man libglib2.0-dev libgudev-1.0-dev libmbim-glib-dev libqrtr-glib-dev (Ubuntu/Debian)
git clone https://gitlab.freedesktop.org/mobile-broadband/libqmi.git
cd libqmi
meson setup build --prefix=/usr --buildtype=release
sudo ninja -j$(nproc) -C build
sudo ninja -C build install
```
